name: 🐞 Bug Report
description: Report an issue or unexpected behavior in the system.
title: "[Bug]: "
labels: ["bug", "defect"]
projects: []
assignees:
  - loadevent
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please fill out the details below to help us identify and fix the problem quickly.
  - type: input
    id: defect-id
    attributes:
      label: Defect ID
      description: Unique identifier for the defect / bug.
      placeholder: "e.g., Defect-001"
    validations:
      required: true
      
  - type: input
    id: detected-by
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: input
    id: summary
    attributes:
      label: Defect / Bug summary
      description: Provide a short, clear summary of the bug
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

