name: 🐞 Bug Report
description: Report an issue or unexpected behavior in the system.
title: "[Bug]: "
labels: ["bug", "defect"]
projects: [""]
assignees:
  - loadevent
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please fill out the details below to help us identify and fix the problem quickly.
  - type: input
    id: defect-id
    attributes:
      label: Defect ID
      description: Unique identifier for the defect / bug.
      placeholder: "e.g., Defect-001"
    validations:
      required: true
  

