name: 🐞 Bug Report
description: Report an issue or unexpected behavior in the system.
title: "[Bug]: "
labels: ["bug", "defect"]
projects: ["loadevent/18"]
assignees:
  - loadevent
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please fill out the details below to help us identify and fix the problem quickly.
  - type: input
    id: defect-id
    attributes:
      label: Defect ID
      description: Unique identifier for the defect / bug.
      placeholder: "e.g., Defect-001"
    validations:
      required: true
  - type: input
    id: detected-by
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: summary
    attributes:
      label: Defect / Bug summary
      description: Provide a short, clear summary of the bug
      placeholder: "e.g., App crashes when clicking the save button"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List step-by-step instructions to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "It should..."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, it..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version /Build
      description: What version of our software are you running?
    validations:
      required: true
  - type: input
    id: test-case-id
    attributes:
      label: Linked Test Case ID
      description: Which test case was executed?
    validations:
      required: false
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Provide environment details 
      options:
        - Test
        - UAT
        - Pre-Production
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: (Eg. Functional, Performance...)
      options:
        - Functional
        - Performance
        - Usability
        - Security
        - Compatibility 
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
