name: 🐞 Bug Report
description: Report an issue or unexpected behavior in the system.
title: "[Bug]: "
labels: ["bug", "defect"]
projects: [""]
assignees:
  - loadevent
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please fill out the details below to help us identify and fix the problem quickly.
  - type: input
    id: defect-id
    attributes:
      label: Defect ID
      description: Unique identifier for the defect / bug.
      placeholder: "e.g., Defect-001"
    validations:
      required: true
  - type: input
    id: detected-by
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: summary
    attributes:
      label: Defect / Bug summary
      description: Provide a short, clear summary of the bug
      placeholder: "e.g., App crashes when clicking the save button"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue in detail. What is happening and what should happen instead?
      placeholder: "Detailed steps to reproduce..."
    validations:
      required: true
