name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement", "feature"]
projects: ["Jet Skill LMS"]
assignees:
  - loadevent
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        Please fill out the details below to help us understand and prioritize your request.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Provide a short, clear summary of the feature.
      placeholder: "e.g., Add dark mode support"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Explain the feature in detail. Include examples, diagrams, or references if applicable.
      placeholder: "Describe what the feature should do..."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why is this feature needed?
      description: Explain the problem this feature solves or the value it adds.
      placeholder: "It would help because..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: List any alternative solutions or workarounds you've considered.
      placeholder: "I could also..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
      placeholder: "Screenshots, designs, or related links..."
    validations:
      required: false
