// <auto-generated />
using System;
using Jet_Skills_SMS_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jet_Skills_SMS_.Migrations
{
    [DbContext(typeof(JetSkillsDbContext))]
    [Migration("20250904092715_adminKeys")]
    partial class adminKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.HasKey("AdminId", "Email");

                    b.HasIndex("UserType");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("course_id");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("course_name");

                    b.Property<int?>("DurationYears")
                        .HasColumnType("int")
                        .HasColumnName("duration_years");

                    b.Property<string>("FacultyId")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("faculty_id");

                    b.HasKey("CourseId")
                        .HasName("PK__Courses__8F1EF7AE1FFFE39B");

                    b.HasIndex("FacultyId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("course_id");

                    b.Property<DateOnly?>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Enrollme__6D24AA7A6F9440BB");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Faculty", b =>
                {
                    b.Property<string>("FacultyId")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("faculty_id");

                    b.Property<string>("DeanName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dean_name");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("faculty_name");

                    b.HasKey("FacultyId")
                        .HasName("PK__Facultie__7B00413C756BCC2F");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Lecturer", b =>
                {
                    b.Property<int>("LecturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lecturer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LecturerId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FacultyId")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("faculty_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.HasKey("LecturerId")
                        .HasName("PK__Lecturer__D4D1DAB1C199F4FB");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UserType");

                    b.HasIndex(new[] { "Email" }, "UQ__Lecturer__AB6E61640D7E42F3")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.LecturerModule", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("academic_year");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int")
                        .HasColumnName("lecturer_id");

                    b.Property<string>("ModuleId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("module_id");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Lecturer__DA8918149D103725");

                    b.HasIndex("LecturerId");

                    b.HasIndex("ModuleId");

                    b.ToTable("LecturerModule");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Module", b =>
                {
                    b.Property<string>("ModuleId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("module_id");

                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("course_id");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("module_name");

                    b.Property<int?>("Semester")
                        .HasColumnType("int")
                        .HasColumnName("semester");

                    b.HasKey("ModuleId")
                        .HasName("PK__Modules__1A2D0653F91B8B21");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__2A33069AB3CD0E19");

                    b.HasIndex("UserType");

                    b.HasIndex(new[] { "Email" }, "UQ__Students__AB6E616418172070")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Admin", b =>
                {
                    b.HasOne("Jet_Skills_SMS_.Models.UserType", "UserTypeNavigation")
                        .WithMany("Admins")
                        .HasForeignKey("UserType");

                    b.Navigation("UserTypeNavigation");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Course", b =>
                {
                    b.HasOne("Jet_Skills_SMS_.Models.Faculty", "Faculty")
                        .WithMany("Courses")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK__Courses__faculty__29572725");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Enrollment", b =>
                {
                    b.HasOne("Jet_Skills_SMS_.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Enrollmen__cours__33D4B598");

                    b.HasOne("Jet_Skills_SMS_.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Enrollmen__stude__32E0915F");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Lecturer", b =>
                {
                    b.HasOne("Jet_Skills_SMS_.Models.Faculty", "Faculty")
                        .WithMany("Lecturers")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK__Lecturers__facul__300424B4");

                    b.HasOne("Jet_Skills_SMS_.Models.UserType", "UserTypeNavigation")
                        .WithMany("Lecturers")
                        .HasForeignKey("UserType")
                        .HasConstraintName("FK__Lecturers__user___4AB81AF0");

                    b.Navigation("Faculty");

                    b.Navigation("UserTypeNavigation");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.LecturerModule", b =>
                {
                    b.HasOne("Jet_Skills_SMS_.Models.Lecturer", "Lecturer")
                        .WithMany("LecturerModules")
                        .HasForeignKey("LecturerId")
                        .HasConstraintName("FK__LecturerM__lectu__37A5467C");

                    b.HasOne("Jet_Skills_SMS_.Models.Module", "Module")
                        .WithMany("LecturerModules")
                        .HasForeignKey("ModuleId")
                        .HasConstraintName("FK__LecturerM__modul__36B12243");

                    b.Navigation("Lecturer");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Module", b =>
                {
                    b.HasOne("Jet_Skills_SMS_.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Modules__course___2C3393D0");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Student", b =>
                {
                    b.HasOne("Jet_Skills_SMS_.Models.UserType", "UserTypeNavigation")
                        .WithMany("Students")
                        .HasForeignKey("UserType")
                        .HasConstraintName("FK__Students__user_t__49C3F6B7");

                    b.Navigation("UserTypeNavigation");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Faculty", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Lecturer", b =>
                {
                    b.Navigation("LecturerModules");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Module", b =>
                {
                    b.Navigation("LecturerModules");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Jet_Skills_SMS_.Models.UserType", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Lecturers");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
